log_level: INFO


telegram:
  bot:
    token: 382198473:AAFAJf8XlOk_9CyUOQ98QnwlncmfjKd6ec8  # rr test bot


avatar:
  position:
    x: 50  # percent 0-100
    y: 83  # percent 0 (top) .. 100 (bottom)
  scale: 25  # percent of max dimension