# rename it to "config.yaml"

log_level: INFO


telegram:
  bot:
    token: FILL_ME_PLEASE

  channels:
    - type: telegram
      name: -10012344   # fill this (integer number) instructions: https://stackoverflow.com/a/39943226
      lang: eng


data_source:
  defi_pulse:
    api_token: FILL_ME_PLEASE
    fetch_period: 1h

  coin_gecko:
    fetch_period: 60


notifications:
  price:
    time_of_day: "12:00"
    ath:
      stickers:
        - CAACAgIAAxkBAAIPuF-zvf5B1guBsIC8YqQE7jHnNP39AAJkBQACP5XMCgTLN7BUdOcAAR4E
        - CAACAgIAAxkBAAIPvF-zvjn4-XPhcr-M06zZUUvwF700AAIpAAM7cR8iDQ6e_eGNDLUeBA
        - CAACAgIAAxkBAAIPvl-zvkRAYSkjyVNi9QxzovYSDK4DAAKqBQACP5XMCpXI5d6t1J7eHgQ
        - CAACAgIAAxkBAAIPwF-zvlRib5d5xSR1kWEwr0rpTJbIAAISAAP3F4Erq1mdGtkjKYUeBA
        - CAACAgIAAxkBAAIPol-zvRRRPSdC-Sr4lqhKsfNWWh3qAAJPAQACIjeOBHyVl0hMcbwXHgQ
        - CAACAgIAAxkBAAIPsF-zvVaSci3nhGf2-6l2YUEKcMKnAAICAAMUkqgdqsiIC2ZyV0oeBA
        - CAACAgIAAxkBAAIPsl-zvWI-Ihnnh0BSm6BM6DpYjYuJAAISAAP3F4Erq1mdGtkjKYUeBA
        - CAACAgIAAxkBAAIPuF-zvf5B1guBsIC8YqQE7jHnNP39AAJkBQACP5XMCgTLN7BUdOcAAR4E
        - CAACAgIAAxkBAAIPvl-zvkRAYSkjyVNi9QxzovYSDK4DAAKqBQACP5XMCpXI5d6t1J7eHgQ
        - CAACAgIAAxkBAAIPwF-zvlRib5d5xSR1kWEwr0rpTJbIAAISAAP3F4Erq1mdGtkjKYUeBA
        - CAACAgIAAxkBAAIPwl-zyp2DJdPINcX6h0ZGesaakaMnAAJ9AwACbbBCA70TLvm2TbpTHgQ
        - CAACAgIAAxkBAAIPyV-zzEtVsFiaAWTVrJ8ROptFYUqjAAJFAAP3F4ErgJFXK7AarK4eBA
        - CAACAgIAAxkBAAJQsV_4emucc8THq6MbytL5PcclEG4NAAKMCwACLw_wBoRsyFANo_xWHgQ
        - CAACAgIAAxkBAAJQs1_4epK5KoxnhAJ3R5akKXpIfN1nAAKfAQACFkJrCmWMf9oXSSAlHgQ
        - CAACAgUAAxkBAAJQtV_4eqqciwvp9NCRdslyOoCKsOSaAAIdAAPRi-Yk3GCYqQrnOzceBA
        - CAACAgIAAxkBAAJQt1_4esnnDoR3NjLpgKHilirOZWybAAJsAAMUkqgduXN64vXUPDceBA
        - CAACAgUAAxkBAAJQuV_4eupYryWgJXeuLUu8xQsrfiBEAAIMAAPRi-Ykfll73qqZa3keBA
        - CAACAgUAAxkBAAJQu1_4eu8AAVG_deJgnwdKZcU9bsMYdgACGQAD0YvmJI2929l8C8ycHgQ
        - CAACAgUAAxkBAAJQvV_4ev8v5xXq_gABGb1O3g7UzdcZeAACHAAD0YvmJMnrKQclfN7VHgQ
        - CAACAgIAAxkBAAKYGmAxSKM0wcVUir6olqJ8GUILs7PEAAI2AwACnNbnCqJFmbVS5co5HgQ
        - CAACAgIAAxkBAAKYGGAxSJmnC6uu7NyUkjwD2uQ2k8Z3AAITAwACnNbnCv7sKag-OU5jHgQ
        - CAACAgIAAxkBAAKYFmAxSI6jczWX5DMkK9N7D5U3arbZAAIDAQACVp29CgLl0XiH5fpPHgQ
        - CAACAgIAAxkBAAKYHGAxSOVmUIJnSALFOQmjvDUUhE8SAAIvAwACnNbnCp7xW8futGVHHgQ
        - CAACAgIAAxkBAAKYHmAxSPKMMhaVi529pPU-_ROhQlB_AAIUAAM7YCQUKWeBEgL3yOoeBA
        - CAACAgIAAxkBAAKYImAxSRLALhyBbigWlLSUzrLaf84mAAJVBgAC-gu2CMHtlUjSy95hHgQ
        - CAACAgIAAxkBAAKYJGAxSSC1U9D67zyg-7RJfjkork8EAAKMAAMWQmsKQo7-Yhc9TeIeBA
        - CAACAgIAAxkBAAKYJmAxST6CTOiOStfQ9CH7hqLiv0iWAAL8BgACRvusBG1XSZhZ24v-HgQ
